version: "3"
services:
        db:
                image: mysql:latest
                container_name: team8-mysql
                ports:
                        - "3306:3306"
                environment:
                        MYSQL_ROOT_PASSWORD: "team8!"
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci
                volumes:
                        - /home/ubuntu/docker/mysql/data:/var/lib/mysql
                        - /home/ubuntu/docker/mysql/config:/etc/mysql/conf.d


